// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQW7gnEjmxFWnTF6JNwiJzVJYtlLO4YM8',
    appId: '1:659739609918:web:8ddad0fadb86d122f87a6f',
    messagingSenderId: '659739609918',
    projectId: 'quaha-55d7a',
    authDomain: 'quaha-55d7a.firebaseapp.com',
    storageBucket: 'quaha-55d7a.appspot.com',
    measurementId: 'G-FSB9RR0MWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_nY-golImAqu5gnHZ12Aju5e5uRqDTI',
    appId: '1:659739609918:android:b4ec61ea2577172df87a6f',
    messagingSenderId: '659739609918',
    projectId: 'quaha-55d7a',
    storageBucket: 'quaha-55d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aIM5yKoKExdDWR2JSbhDbtAvHt9cQq0',
    appId: '1:659739609918:ios:fb14cf2001e7f47bf87a6f',
    messagingSenderId: '659739609918',
    projectId: 'quaha-55d7a',
    storageBucket: 'quaha-55d7a.appspot.com',
    iosBundleId: 'com.example.quaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3aIM5yKoKExdDWR2JSbhDbtAvHt9cQq0',
    appId: '1:659739609918:ios:7e340505f94d84bdf87a6f',
    messagingSenderId: '659739609918',
    projectId: 'quaha-55d7a',
    storageBucket: 'quaha-55d7a.appspot.com',
    iosBundleId: 'com.example.quaha.RunnerTests',
  );
}
